//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalForm
    {
        public int RentalFormId { get; set; }
        public Nullable<int> CarsFormId { get; set; }
        public Nullable<int> CustomerFormId { get; set; }
        public Nullable<int> InsuranceCompanyFormId { get; set; }
        public Nullable<int> AppUserFormId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Wage { get; set; }
        public Nullable<int> VATRate { get; set; }
        public Nullable<decimal> VATWage { get; set; }
        public Nullable<decimal> DailyWage { get; set; }
        public Nullable<decimal> InsuranceWage { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual AppUserForm AppUserForm { get; set; }
        public virtual CarsForm CarsForm { get; set; }
        public virtual CustomerForm CustomerForm { get; set; }
        public virtual InsuranceCompanyForm InsuranceCompanyForm { get; set; }
    }
}
